name: cralwer

on:
  push:
    branches: [main]
  
jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    - name: test1
      env:
        github_token: ${{ secrets.GITHUBTOKEN }}
      run: |
        python cralwer.py
